### PR TITLE
Adding Docker Registry

### PR DESCRIPTION
**Pull request by gogodi91**
This depends on a custom registry image.

### CODE REVIEW

**Comment by kramos** [comment]
@gogodi91  thanks for this PR!  @anton-kasperovich I heard you are working on merging it.  How's it going?

**Comment by kramos** [comment]
Also does this PR need merging with this: #91

**Comment by anton-kasperovich** [comment]
First of all, i want to say @gogodi91 thank you, your pull request gave as great opportunity to start thinking and talking about Docker Registry as part of ADOP. Unfortunately solution from this Pull Request was built on top of custom docker image which is totally fine for specific project needs, but we found a bit different way how to implement Docker Registry via official Docker image without any changes in that area basically. We moved generation of SSL certificates out of the image and made it as part of external bash script, just yesterday i pushed latest version (for now) in my fork - https://github.com/anton-kasperovich/adop-docker-compose/commit/777a9da254cde978bec8841439c1d428238b0ccf

I think we can close both pull requests (as for #91 person can't continue his work on that pull request) in prior of my which i will create today as well.

**Comment by anton-kasperovich** [comment]
As Docker Registry and Certbot script was implemented in https://github.com/Accenture/adop-docker-compose/pull/123 PR, i'm closing this one.

Again, thank you @gogodi91 !

**Pull request closed without merging**
