### PR TITLE
Added script to allow setting of passwords and updated compose file to include new env variables

### PR DESCRIPTION
**Pull request by dsingh07**

### CODE REVIEW

**Comment by kramos** [comment]
Looks great.  Build failed, but I suspect the Dockerhub build for the Jenkins container was just too slow.

Two suggestions 
- it looks like you are using the admin password for MYSQL_ROOT_PASSWORD.  Are there any advantages to these passwords matching?  It would be more secure to have a different password.  
- it looks like admin.config.sh is overlapping with env.config.sh.  I suggest admin.config.sh should be limited to the master username and password, and the PASSWORD_JENKINS etc. should be in env.config.sh

**Comment by nickdgriffin** [comment]
DockerHub won't have built anything, this is a pre-emptive PR as I have to
accept all the image PRs tomorrow - and this gets a pre-test once the new
tags are published.

**Comment by nickdgriffin** [comment]
So, we've decided that "admin.config.sh" should be renamed to "credentials.config.sh" to make it a bit clearer what its purpose is. Dharmanshu also pointed out that we can't move the functionality into "env.config.sh" because otherwise everytime someone reruns the script it'll generate a new password for the tools that Compose will pick up but it won't match what is in LDAP (because it only adds, not modifies).

**Comment by kramos** [comment]
Did we stop the admin password matching MYSQL_ROOT_PASSWORD?

Also,  I think we've ended up with two approaches.  env.config.sh has passwords deliberately bad that users are supposed to override e.g. SONAR_MYSQL_PASSWORD.  credentials.config.sh generates some other credentials.  I think moving all passwords to credentials.config.sh will resolve this.  

Does this make sense?

**Comment by nickdgriffin** [comment]
Yep, I expect there are some not covered (yet). This was initially for
removing john.smith and I allowed it to creep to hit the other LDAP users
so that they weren't equally vulnerable, but it could also be applied to
the internal only passwords such as for the DB as you've mentioned.

**Pull request merged**
