### PR TITLE
Changed port instruction format in docker-compose file according to the latest format

### PR DESCRIPTION
**Pull request by svscorp**
Hi team,

This is an important change that is blocking adop installation using existing docker-compose.yml on a server or Swarm API where docker-compose is v1.13+

Can it be merged to master?

@nickdgriffin @SachinKSingh28

### CODE REVIEW

**Comment by nickdgriffin** [comment]
Hi Ilia,

This is a duplication of https://github.com/Accenture/adop-docker-compose/pull/229 so my comment still stands - has this been tested against the version of Docker Compose stated in our pre-requisites as the version we are compatible with?

Thanks,
Nick

**Comment by arthur-kovalenko** [comment]
@nickdgriffin I tested this PR with Docker 1.10/1.12/1.13/17.06 and Docker compose v1.9.0, and it is working

**Comment by svscorp** [comment]
Thanks @arthur-kovalenko ! Was on vacation with no chance to test this.

**Comment by nickdgriffin** [comment]
Cool thanks @arthur-kovalenko , I'll merge then.

**Pull request merged**
