### PR TITLE
Fix for Issue #228: "Docker Compose File has Incorrect Port Format #228"

### PR DESCRIPTION
**Pull request by garystafford**
Fix for Issue: "Docker Compose File has Incorrect Port Format #228"

### CODE REVIEW

**Comment by nickdgriffin** [comment]
Hello,

Has this been tested against older versions of Docker Compose?

Also, can the three commits to do with the engine URL be removed from this PR as they aren't related. It will also need rebasing on master please.

Thanks,
Nick

**Comment by svscorp** [comment]
I think this issue should be closed, because fix was merged in #241

Thank you for your contribution @garystafford. Your change also shows adding "engine-install" key to the provisioning on AWS that leads to webarchive. Is there a particular reason?

**Comment by nickdgriffin** [comment]
@svscorp That was a workaround for the fact that Docker changed the install script so that it wasn't compatible with the AMI that Docker Machine would create.

**Comment by RobertNorthard** [comment]
Closing as resolved in https://github.com/Accenture/adop-docker-compose/pull/241. Thank you @garystafford for the contribution.

**Pull request closed without merging**
