### PR TITLE
Updating GitHub Pages links to HTTPS

### PR DESCRIPTION
**Pull request by nickdgriffin**
I've updated the HTTP links to HTTPS, because who doesn't like a bit of encryption on their HTTP traffic?

I also noticed that there's a setting on the repository to enforce it so I've set that as well, but I think it can't hurt to update the URLs anyway just to make a point.

### CODE REVIEW

**Comment by anton-kasperovich** [comment]
@nickdgriffin rebase :)

**Comment by svscorp** [comment]
+1

**Comment by nickdgriffin** [comment]
Done @anton-kasperovich

**Comment by anton-kasperovich** [comment]
LGTM.

**Pull request merged**
