### PR TITLE
Improving contribution guidelines

### PR DESCRIPTION
**Pull request by nickdgriffin**
I've added a few extra guidelines to help project maintainers to process pull requests.

### CODE REVIEW

**Comment by svscorp** [comment]
Hi @nickdgriffin,

Can we merge this one? Otherwise it's just hanging in PRs ;)

**Comment by SachinKSingh28** [comment]
LGTM.

**Comment by nickdgriffin** [comment]
Done @SachinKSingh28

**Comment by anton-kasperovich** [comment]
Thank you @nickdgriffin

**Pull request merged**
