### PR TITLE
Change NGINX countdown timer to pretty one

### PR DESCRIPTION
**Pull request by anton-kasperovich**
Just to make all countdown timers looks the same...

### CODE REVIEW

**Comment by kramos** [comment]
Hi @anton-kasperovich I admire your dedication to consistency!  Only one small concern with this, TOOL_SLEEP_TIME = 30 seconds, so you are increasing the NGINX sleep from 5 to 30 with the above change.

Would this be better?

    until [[ $(curl -I -s -u ${INITIAL_ADMIN_USER}:${INITIAL_ADMIN_PASSWORD_PLAIN} http://${TARGET_HOST}/|head -n 1|cut -d$' ' -f2) == 200 ]]; do pretty_sleep 5 Nginx; done

(I tested it).

**Comment by anton-kasperovich** [comment]
Hi @kramos , on my environment, there's not much difference, as it's sleeps more than ~60 seconds, but it looks like on Travis CI it's a bit faster and totally make sense to revert to 5 seconds sleep. Good point, updated this PR.

**Comment by kramos** [comment]
LGTM

**Comment by nickdgriffin** [comment]
LGTM.

**Pull request merged**
