### PR TITLE
Bumping Jenkins image version to 0.2.7

### PR DESCRIPTION
**Pull request by nickdgriffin**
Bumping Jenkins image version to 0.2.7, in support of Accenture/adop-platform-management#11

### CODE REVIEW

**Comment by anton-kasperovich** [comment]
Tested on a fresh stack, was able to load plat-man w/o specific version. Could you please rebase this PR? Thank you in advance!

**Comment by nickdgriffin** [comment]
@anton-kasperovich Done :)

**Comment by RobertNorthard** [comment]
This will be merged once DOA changes are made.

**Comment by RobertNorthard** [comment]
Looks good to me. This can now be merged.

**Pull request merged**
