### PR TITLE
Travis: Upgrading Compose to 1.6.2 for bug fixes

### PR DESCRIPTION
**Pull request by nickdgriffin**
Upgrading Compose to 1.6.2 for bug fixes in Travis

### CODE REVIEW

**Comment by anton-kasperovich** [comment]
@nickdgriffin Is it means that we should add information in README that we would support only Docker Compose:
**>= v1.6.2 ?**

**Comment by nickdgriffin** [comment]
I think that'd be sensible, yes. Considering we already use 1.6.0 in Travis I was thinking of capturing the baseline dependencies as part of #127 anyway seeing as that's when they could all change.

The major issue we've had with dependencies was #115 which I fixed under #131 .

**Comment by nickdgriffin** [comment]
Adding the version requirements, although it'll need the site to be published to be visible but we can do that when 0.2.1 is closed out I think.

**Comment by anton-kasperovich** [comment]
LGTM.

**Pull request merged**
