### PR TITLE
Added info about Pluggable SCM

### PR DESCRIPTION
**Pull request by kristapsm**

### CODE REVIEW

**Comment by anton-kasperovich** [comment]
This PR is outdated and contains broken urls. @nickdgriffin @RobertNorthard should we create an issue and create new PR?

**Comment by dsingh07** [comment]
Can we not just fix the URLs in this PR? The main docs should link to the cartridge cookbooks, and then, the pluggable scm docs.

**Comment by anton-kasperovich** [comment]
@kristapsm could you please provide an update? Thank you!

**Comment by anton-kasperovich** [comment]
LGTM. Thank you @kristapsm !

**Pull request merged**
