### PR TITLE
Nginx image update to last bugfix version

### PR DESCRIPTION
**Pull request by svscorp**
Changes:

NGINX image version changed from 0.3.0 to 0.3.2

### CODE REVIEW

**Comment by svscorp** [comment]
@dsingh07 @anton-kasperovich @SachinKSingh28 @nickdgriffin 

Should be ok to merge, any objections?

**Comment by RobertNorthard** [comment]
@Accenture/devops-platform-l2 please can this be reviewed and tested?

**Comment by subodh-hatkar** [comment]
Tested and worked. ADOP comes up as expected and can see the ADOP Dashboard.

**Comment by RobertNorthard** [comment]
@svscorp please can you rebase this?

**Comment by SachinKSingh28** [comment]
@RobertNorthard It seems the version for adop-nginx was updated with sonarqube upgrade to fix the navigation issue in https://github.com/Accenture/adop-docker-compose/pull/255 . I believe this can be closed.

**Comment by RobertNorthard** [comment]
Closing PR are resolved in https://github.com/Accenture/adop-docker-compose/pull/255

**Pull request closed without merging**
