### PR TITLE
fix hardcoded usernames for gerrit and jenkins

### LINKED ISSUE #212: Hardcoded usernames in cmd/compose
Hi,

Please pay attention on hardcoded usernames when linking this repository from your own scripts:

https://github.com/Accenture/adop-docker-compose/blob/master/cmd/compose#L156
https://github.com/Accenture/adop-docker-compose/blob/master/cmd/compose#L157
https://github.com/Accenture/adop-docker-compose/blob/master/cmd/compose#L164

### PR DESCRIPTION
**Pull request by avoidik**
Attempt to fix #212

### CODE REVIEW

**Comment by svscorp** [comment]
Thank you for your suggested change.

I think it's not a good idea to use platform admin credentials (as variables here). The right thing here would be to replace hardcoded "jenkins" and "gerrit" usernames with something like `${JENKINS_PLATFORM_USERNAME}` and `${GERRIT_PLATFORM_USERNAME}` to have in the end:

`${JENKINS_PLATFORM_USERNAME}:${PASSWORD_JENKINS}@...`
`${GERRIT_PLATFORM_USERNAME}:${PASSWORD_GERRIT}@...`

It's also important to include changes into platform and env.config.sh:

````
   # env.config.sh

   export GERRIT_PLATFORM_USERNAME="gerrit"
   export JENKINS_PLATFORM_USERNAME="jenkins"
````

Can you please make this changes and rebase?

**Comment by avoidik** [comment]
sure

**Comment by avoidik** [comment]
@svscorp done

**Comment by svscorp** [comment]
Hey @avoidik, it looks good now. Thank you!

@nickdgriffin @anton-kasperovich Hi team, can you pls have a look and merge if it is ok?

**Comment by svscorp** [comment]
@avoidik oh wait a second, I think branch got outdated, can you please rebase again? :)

**Comment by SachinKSingh28** [comment]
LGTM. I have tested this change and I was able to launch ADOP stack on virtualbox and on an EC2 instance.

**Pull request merged**
