### PR TITLE
Clean up of both docker-machine existing test and create command itself.

### PR DESCRIPTION
**Pull request by robwells57**
Made test for existing docker-machine more specific.

Also cleaned up docker-machine create commands to avoid duplication and be more maintainable.

### CODE REVIEW

**Comment by nickdgriffin** [comment]
Hi Rob,

Can you apply the fix to the quickstart.sh script, rebase against the latest, and squash the commits please?

Thanks,
Nick

**Comment by robwells57** [comment]
Ok.

**Comment by robwells57** [comment]
Using more specific check for existing docker machine.

Changed layout of usage printout and commands to be more readable.

**Comment by nickdgriffin** [comment]
LGTM, thanks!

**Pull request merged**
