### PR TITLE
Google Cloud deployment option in quickstart.sh 

### PR DESCRIPTION
**Pull request by gokhankuyucak**
Added a "-t google" option in quickstart.sh, some parameters specific to Google Cloud, and a "provision_google()" function to implement the Docker Machine call with the[ Google Cloud driver](https://docs.docker.com/machine/drivers/gce). The usage text is modified as well.

Google Cloud specific parameters are:
-i google-project ID: required The ID of your project to use when launching the instance. With gcloud, use "gcloud projects list" to list your ID's
-l google-disk-size: Disk size of the instance. Default: 10 GB.

You should get authorization by typing gcloud auth login
or setting GOOGLE_APPLICATION_CREDENTIALS environment variable before running script.

### CODE REVIEW

**Comment by kramos** [comment]
I tested this and raised a PR with some suggestions:
https://github.com/gokhankuyucak/adop-docker-compose/pull/1

**Comment by kramos** [comment]
Sorry @gokhankuyucak  I found it wasn't possible to re-run quickstart and also the certbot job for docker registry didn't work.  Hence I've made fixes on my fork.  Please can you tick the box on this PR so that I can edit it and I'll get it merged.  Thanks for this!

**Comment by gokhankuyucak** [comment]
Sorry @kramos but 
_

> Please can you tick the box on this PR so that I can edit it and I'll get it merged.

_ 

I didn't get this part, what should I do? Thanks

**Comment by kramos** [comment]
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by gokhankuyucak** [comment]
Thanks for the link as I checked  "Allow edits from maintainers" checkbox is already ticked. Could you please try again?
Allow edits from maintainers.

**Comment by kramos** [comment]
Sorry for the very slow response!  It looks like you need to also explicitly grant me access to push to your fork please: https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/

By the way, I just rebased from master to my branch for this PR and a stack created in GCP like a dream.  Well actually the only snag is having to manually open port 80...  any thoughts on that?

**Comment by nickdgriffin** [comment]
On port 80, there is a similar "issue" when doing it in AWS however often it's done in an account where the SG has already been manually edited.

One workaround could be to use the gcloud CLI to open the port although like in AWS it might be that the user deploying /C might not have permission to.

**Comment by kramos** [comment]
HI @nickgriffin, I did exactly that, if quickstart can find the gcloud CLI, it should succeed at opening  port 80.

To test this PR:
```
$ ./quickstart.sh  -t gcp -i <GOOGLE_PROJECT_ID> -m <CHOSEN MACHINE NAME:
```

**Pull request closed without merging**
