### PR TITLE
provide kubernetes support

### PR DESCRIPTION
**Pull request by janwillies**
This PR provides kubernetes support for ADOP. Please refer to the readme for detailed instructions. There's also a doc how to port from docker-compose to kubernetes.
### Features:
- install on any kubernetes cluster (local, or remote)
- overwrite default values on the commandline or via separate values file
- installation without cloning a git repository
### Assumptions:
- kubernetes v1.2 at minimum
- helm
### ToDo:
- test everything more properly
- fix selenium link (https://github.com/Accenture/adop-docker-compose/issues/50)

There were only two adop components which needed patching:
- patched adop-nexus because LDAP_PORT variable conflicts with kubernetes
- patched adop-nginx to start even though kibana is not available

will send PR to the respective repos next.

### CODE REVIEW

**Comment by mcroker** [comment]
Jan - I think you suggested we weren't handling LDAP decoding properly... did you raise an issue for this?  You suggested 'correct fix' sounded better than what we ended up with.

**Comment by nickdgriffin** [comment]
I'm thinking it might be appropriate for this to sit in it's own repository that can be combined with adop-docker-compose so you can get everything in one box. My reasoning is that:

- The CLI should probably be independent of everything
- Kubernetes and Docker Compose are just two ways to launch ADOP
- You could use the CLI to "pick" which way you want and it can clone the other repo in, which brings in specific CLI commands as well as whatever other stuff is needed

This also means that ultimately the CLI needs to move out of this repo and instructions need updating, unless we accept that Docker Compose is the "default" method.

**Comment by janwillies** [comment]
I filed an issue here: https://github.com/Accenture/adop-ldap/issues/5

What I did here is to to untangle the bash scripts and provide a declarative approach. With some more work for example, you could deploy adop with a different jenkins password like this: `helm install adop/adop-0.1.0 -e JENKINS_PASSWORD=foobar`, or even put them in a `values.yaml`-file. There is no bash-logic or whatsoever involved. Plus you don't need to clone a repo to deploy adop.

**Comment by kramos** [comment]
Hi @janwillies a very belated thanks so much for creating this pull request.  We're very excited to see that you have run ADOP on Kubernetes.  I think it is distinctly possible that within the not too distant future ADOP _might_ be updated to run by default on Kubernetes rather than Docker Swarm.  That said I think today it would raise the barrier of adoption too high for many users (who don't have a Kubernetes instance at their disposal).  Whilst docker-compose and helm / Kubernetes configuration are so different I think keeping both of them in sync might be a maintenance overhead that we cannot keep up with.  NB. the [ADOP Roadmap](https://github.com/Accenture/adop-docker-compose/wiki/Roadmap) currently has nothing in it about this pull request.  [Gitter](https://gitter.im/Accenture/ADOP) is perhaps one place to discuss this point (or here as well).

**Pull request closed without merging**
