### PR TITLE
upgrade nodejs to 6.9.4 LTS

### PR DESCRIPTION
**Pull request by m4m51m**

### CODE REVIEW

**Comment by anton-kasperovich** [comment]
@m4m51m may be we were waiting too long, to accept this pull request, but as far as i can see per official https://nodejs.org/en/ website, latest LTS is 6.9.4 now, could you please update the PR on the latest LTS version? Please, don't forget to squash commits and I will be happy to merge this PR right after. Thank you in advance!

**Comment by m4m51m** [comment]
@anton-kasperovich  I've updated the PR

**Comment by anton-kasperovich** [comment]
@m4m51m nice, but i can still see 2 commits - https://github.com/Accenture/adop-docker-compose/pull/173/commits could you please also squash it? "git rebase" command

**Comment by m4m51m** [comment]
@anton-kasperovich  rebase done

**Comment by anton-kasperovich** [comment]
Great, I will test this ASAP and accept, thank you!

**Comment by anton-kasperovich** [comment]
```
Unpacking https://nodejs.org/dist/v6.9.4/node-v6.9.4-linux-x64.tar.gz to /tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/ADOP_NodeJS on Swarm_Slave-20385222
$ /tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/ADOP_NodeJS/bin/npm install -g grunt-cli@~0.1.13 bower@~1.3.12 plato@~1.2.1
/usr/bin/env: node: No such file or directory
[npm_test] $ /bin/sh -xe /tmp/hudson4373455909764583542.sh
+ npm install
npm WARN lifecycle todo-backend-client@1.0.0~prepublish: cannot run in wd %s %s (wd=%s) todo-backend-client@1.0.0 grunt /workspace/ExampleWorkspace/ExampleProject/npm_test
Finished: SUCCESS
```

It works as expected. LGTM.

**Pull request merged**
