### PR TITLE
12 subnet option

### PR DESCRIPTION
**Pull request by robwells57**
Initial version of new zone commend line option.

### CODE REVIEW

**Comment by kramos** [comment]
It seems a shame to add another mandatory argument. Is an alternative that the readme states to create the subnet in az A, else it will need overriding?

**Comment by deors** [comment]
I also think that we should not add more required params unless there is no other options. I think that a sensible default to 'a'  that is overridable would be better.

**Comment by robwells57** [comment]
What if we make the zone optional then and update the README to mention
selecting the 'a'  zone when creating the VPC?

Then, just in case the zone default for the amazonec2 driver changes from
'a' in a future version, we also add a note to the README saying if the
create fails check your availability zone and then rerun the script
specifying the zone using the -z option.

**Comment by nickdgriffin** [comment]
This looks good, and I think addresses both of the above comments from @kramos  and @deors.

Can you remove the merge commit please then I think this is ready to merge?

**Comment by robwells57** [comment]
Cheers Nick.

Will do first thing tomorrow after clarifying with you.

Rob

**Pull request closed without merging**
